package com.jy.fistga.data.source.local.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jy.fistga.data.User;
import com.jy.fistga.data.News;
import com.jy.fistga.data.Channel;

import com.jy.fistga.data.source.local.greendao.UserDao;
import com.jy.fistga.data.source.local.greendao.NewsDao;
import com.jy.fistga.data.source.local.greendao.ChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig channelDaoConfig;

    private final UserDao userDao;
    private final NewsDao newsDao;
    private final ChannelDao channelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(News.class, newsDao);
        registerDao(Channel.class, channelDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
        channelDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

}
